/**
 * SYMETRY ROULETTE — Configuration
 * Fichier administrable : modifiez ce fichier pour changer
 * les valeurs de paris, devises et langues disponibles.
 */

window.RouletteConfig = {

  // ─── VALEURS DE PARIS ─────────────────────────────────
  // Modifier ces valeurs pour changer les jetons disponibles.
  // Le premier élément sera sélectionné par défaut.
  chips: [5, 10, 25, 50, 100],

  // ─── DEVISES ──────────────────────────────────────────
  currencies: [
    { code: 'USD', symbol: '$',  flag: '🇺🇸', name: 'US Dollar'      },
    { code: 'EUR', symbol: '€',  flag: '🇪🇺', name: 'Euro'            },
    { code: 'CHF', symbol: 'Fr', flag: '🇨🇭', name: 'Franc suisse'    },
    { code: 'NGN', symbol: '₦',  flag: '🇳🇬', name: 'Naira nigérian'  },
    { code: 'AOA', symbol: 'Kz', flag: '🇦🇴', name: 'Kwanza angolais' },
    { code: 'MZN', symbol: 'MT', flag: '🇲🇿', name: 'Metical mozamb.' },
  ],

  // ─── LANGUES ──────────────────────────────────────────
  languages: [
    { code: 'fr', label: 'Français',   flag: '🇫🇷' },
    { code: 'en', label: 'English',    flag: '🇬🇧' },
    { code: 'pt', label: 'Português',  flag: '🇵🇹' },
    { code: 'es', label: 'Español',    flag: '🇪🇸' },
    { code: 'sw', label: 'Kiswahili',  flag: '🇰🇪' },
  ],

  // ─── TRADUCTIONS ──────────────────────────────────────
  i18n: {
    fr: {
      balance:      'Solde',
      placeBets:    'Placez vos mises',
      goodLuck:     'Bonne chance…',
      won:          'Gagné !',
      lost:         'Perdu',
      number:       'Numéro',
      spin:         'SPIN',
      clear:        '✕ Effacer',
      rebet:        '↺ Remiser',
      bets:         'mise',
      betsPlural:   'mises',
      total:        'Total',
      insufficiant: 'Solde insuffisant',
      placFirst:    "Placez votre mise d'abord",
      gain:         'Gain',
      jackpot:      '🏆 JACKPOT',
      totalReturn:  'Retour total',
      sound:        'Son',
      language:     'Langue',
      currency:     'Devise',
      menu:         'Menu',
      red:          'Rouge',
      black:        'Noir',
      even:         'Pair',
      odd:          'Impair',
      low:          '1-18',
      high:         '19-36',
      col:          'Col',
    },
    en: {
      balance:      'Balance',
      placeBets:    'Place your bets',
      goodLuck:     'Good luck…',
      won:          'Won!',
      lost:         'Lost',
      number:       'Number',
      spin:         'SPIN',
      clear:        '✕ Clear',
      rebet:        '↺ Rebet',
      bets:         'bet',
      betsPlural:   'bets',
      total:        'Total',
      insufficiant: 'Insufficient balance',
      placFirst:    'Place your bet first',
      gain:         'Win',
      jackpot:      '🏆 JACKPOT',
      totalReturn:  'Total return',
      sound:        'Sound',
      language:     'Language',
      currency:     'Currency',
      menu:         'Menu',
      red:          'Red',
      black:        'Black',
      even:         'Even',
      odd:          'Odd',
      low:          '1-18',
      high:         '19-36',
      col:          'Col',
    },
    pt: {
      balance:      'Saldo',
      placeBets:    'Faça suas apostas',
      goodLuck:     'Boa sorte…',
      won:          'Ganhou!',
      lost:         'Perdeu',
      number:       'Número',
      spin:         'GIRAR',
      clear:        '✕ Limpar',
      rebet:        '↺ Repartir',
      bets:         'aposta',
      betsPlural:   'apostas',
      total:        'Total',
      insufficiant: 'Saldo insuficiente',
      placFirst:    'Faça sua aposta primeiro',
      gain:         'Ganho',
      jackpot:      '🏆 JACKPOT',
      totalReturn:  'Retorno total',
      sound:        'Som',
      language:     'Idioma',
      currency:     'Moeda',
      menu:         'Menu',
      red:          'Vermelho',
      black:        'Preto',
      even:         'Par',
      odd:          'Ímpar',
      low:          '1-18',
      high:         '19-36',
      col:          'Col',
    },
    es: {
      balance:      'Saldo',
      placeBets:    'Haga sus apuestas',
      goodLuck:     'Buena suerte…',
      won:          '¡Ganó!',
      lost:         'Perdió',
      number:       'Número',
      spin:         'GIRAR',
      clear:        '✕ Borrar',
      rebet:        '↺ Repetir',
      bets:         'apuesta',
      betsPlural:   'apuestas',
      total:        'Total',
      insufficiant: 'Saldo insuficiente',
      placFirst:    'Haga su apuesta primero',
      gain:         'Ganancia',
      jackpot:      '🏆 JACKPOT',
      totalReturn:  'Retorno total',
      sound:        'Sonido',
      language:     'Idioma',
      currency:     'Divisa',
      menu:         'Menú',
      red:          'Rojo',
      black:        'Negro',
      even:         'Par',
      odd:          'Impar',
      low:          '1-18',
      high:         '19-36',
      col:          'Col',
    },
    sw: {
      balance:      'Salio',
      placeBets:    'Weka dau lako',
      goodLuck:     'Bahati nzuri…',
      won:          'Umeshinda!',
      lost:         'Umepoteza',
      number:       'Nambari',
      spin:         'ZUNGUKA',
      clear:        '✕ Futa',
      rebet:        '↺ Rudia',
      bets:         'dau',
      betsPlural:   'madau',
      total:        'Jumla',
      insufficiant: 'Salio haitoshi',
      placFirst:    'Weka dau kwanza',
      gain:         'Faida',
      jackpot:      '🏆 JACKPOT',
      totalReturn:  'Jumla ya kurudi',
      sound:        'Sauti',
      language:     'Lugha',
      currency:     'Sarafu',
      menu:         'Menyu',
      red:          'Nyekundu',
      black:        'Nyeusi',
      even:         'Sawa',
      odd:          'Isiyo sawa',
      low:          '1-18',
      high:         '19-36',
      col:          'Saf',
    },
  },
};
